# Generated by Django 4.2.2 on 2023-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrarAves',
            fields=[
                ('id_ave', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_ave', models.CharField(max_length=20)),
                ('nombre_cientifico', models.CharField(max_length=30, null=True)),
                ('imagen_ave', models.ImageField(upload_to='imagenesAves')),
            ],
        ),
    ]
