# Generated by Django 4.2.2 on 2023-06-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdgo', '0002_bird_delete_registraraves'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bird',
            table=None,
        ),
    ]
